version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: '127.0.0.1,localhost'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
    depends_on:
      - redis
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
      - ./media:/app/media

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
